[client]
showErrorDetails = true
# Show Rerun, Auto rerun, Clear cache when not on localhost (e.g. AWS EC2)
toolbarMode = "developer"

[server]
headless = true
port = 8501
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[logger]
level = "info"
